config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  # signup
  get "/signup" => "users#new"
  # if a user signs up incorrectly the url re-renders as /signup
  post "/signup" => "users#create"

  # login
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"

  # logout
  delete "/logout" => "sessions#destroy"

  # omniauth callback routes
  get "/auth/:provider/callback" => "sessions#omnilogin"

  resources :reviews, :movies
  resources :movie_actors, :movie_genres, only: [:destroy]
  resources :actors, :genres, only: [:index]
  resources :users, only: [:show]
  resources :movies, :users, only: [:show] do
    resources :reviews, shallow: true
  end
  resources :actors, :genres, only: [:show] do
    resources :movies, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres, :dependent => :destroy
  validates_presence_of :name

  scope :alpha, -> { order(:name) }
  scope :find_by_name, -> (name) { where("name LIKE ?", name) }
  
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  helper_method :sort_column

  def index
    if params[:name]
      @genres = Genre.find_by_name(params[:name])
    else
      @genres = Genre.order(sort_column + " " + sort_direction)
    end
    @movie = Movie.find_by_id(params[:id])
  end

  def show
    @genre = Genre.find_by_id(params[:id])
  end

  private

    def sort_column
      Genre.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/index.html.erb
<h1>Genres</h1>

<%= form_tag genres_path, :method => :get, :class => "search-form" do %>
  <%= label_tag "Search for a genre:", nil, :class => "col-form-label" %>
  <%= text_field_tag :name, params[:name] %>

  <%= submit_tag "Search", :name => nil, :class => "btn btn-outline-secondary" %>
<% end %>

<br>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th style="width: 50%"><%= sortable("name", "Genre") %><%= sort_image("name") %></th>
      <th style="width: 50%"><%= sortable("movie_count", "Number of Movies") %><%= sort_image("movie_count") %></th>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
      <tr>
      <td><%= link_to genre.name, genre_movies_path(genre) %></td>
      <td><%= genre.movie_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>