config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  # signup
  get "/signup" => "users#new"
  # if a user signs up incorrectly the url re-renders as /signup
  post "/signup" => "users#create"

  # login
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"

  # logout
  delete "/logout" => "sessions#destroy"

  # omniauth callback routes
  get "/auth/:provider/callback" => "sessions#omnilogin"

  resources :reviews, :movies
  resources :movie_actors, :movie_genres, only: [:destroy]
  resources :actors, :genres, only: [:index]
  resources :users, only: [:show]
  resources :movies, :users, only: [:show] do
    resources :reviews, shallow: true
  end
  resources :actors, :genres, only: [:show] do
    resources :movies, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :movie_actors
  has_many :movies, through: :movie_actors, :dependent => :destroy
  validates_presence_of :first_name

  scope :find_by_first_name, -> (first_name) { where("first_name LIKE ?", first_name) }
  scope :find_by_last_name, -> (last_name) { where("last_name LIKE ?", last_name) }

  def full_name
    if self.last_name
      self.first_name + " " + self.last_name
    else
      self.first_name
    end
  end

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  helper_method :sort_column

  def index
    set_actors_array
    @movie = Movie.find_by_id(params[:id])
  end

  def show
    @actor = Actor.find_by_id(params[:id])
  end

  private

    def set_actors_array
      if params[:first_name] && params[:last_name] == ""
        @actors = Actor.find_by_first_name(params[:first_name])
      elsif params[:first_name] == "" && params[:last_name]
        @actors = Actor.find_by_last_name(params[:last_name])
      elsif params[:first_name] && params[:last_name]
        @actors = Actor.find_by_first_name(params[:first_name]) && Actor.find_by_last_name(params[:last_name])
      else
        @actors = Actor.order(sort_column + " " + sort_direction)
      end
    end

    def sort_column
      Actor.column_names.include?(params[:sort]) ? params[:sort] : "last_name"
    end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/index.html.erb
<h1>Actors</h1>

<%= form_tag actors_path, :method => :get, :class => "search-form" do %>
  <%= label_tag "Search for an actor:", nil, :class => "col-form-label" %>
  <%= text_field_tag :first_name, params[:first_name], :placeholder => "First Name" %>
  <%= text_field_tag :last_name, params[:last_name], :placeholder => "Last Name" %>

  <%= submit_tag "Search", :name => nil, :class => "btn btn-outline-secondary" %>
<% end %>

<br>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th style="width: 50%"><%= sortable("last_name", "Name") %><%= sort_image("last_name") %></th>
      <th style="width: 50%"><%= sortable("movie_count", "Number of Movies") %><%= sort_image("movie_count") %></th>
    </tr>
  </thead>
  <tbody>
    <% @actors.each do |actor| %>
      <tr>
      <td><%= link_to actor.full_name, actor_movies_path(actor) %></td>
      <td><%= actor.movie_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>