config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  # signup
  get "/signup" => "users#new"
  # if a user signs up incorrectly the url re-renders as /signup
  post "/signup" => "users#create"

  # login
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"

  # logout
  delete "/logout" => "sessions#destroy"

  # omniauth callback routes
  get "/auth/:provider/callback" => "sessions#omnilogin"

  resources :reviews, :movies
  resources :movie_actors, :movie_genres, only: [:destroy]
  resources :actors, :genres, only: [:index]
  resources :users, only: [:show]
  resources :movies, :users, only: [:show] do
    resources :reviews, shallow: true
  end
  resources :actors, :genres, only: [:show] do
    resources :movies, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  # helper_method :current_movie
  helper_method :sort_column
  before_action :redirect_if_not_admin, only: [:new, :create, :edit, :update]

  def index
    set_movies_array
  end

  def new
    @movie = Movie.new
    @movie.actor_number
    @movie.genre_number
  end

  def create
    @movie = current_user.movies.build(movie_params)
    if @movie.save
      redirect_to movie_path(@movie)
    else
      @movie.actor_number
      @movie.genre_number
      render :new
    end
  end

  def show
    @movie = Movie.find_by_id(params[:id])
  end

  def edit
    # current_movie is impacting blank genre and actor fields
    @movie = Movie.find_by_id(params[:id])
    @movie.actor_number
    @movie.genre_number
  end

  def update
    @movie = Movie.find_by_id(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
      flash[:message] = "Movie successfully updated."
    else
      @movie.actor_number
      @movie.genre_number
      render :edit
    end
  end

  private

    def movie_params
      params.require(:movie).permit(:title, :synopsis, :year, :genres_attributes => [:name], :actors_attributes => [:first_name, :last_name])
    end

    # def current_movie
    #   movie = Movie.find_by_id(params[:id])
    # end

    def sort_column
      Movie.column_names.include?(params[:sort]) ? params[:sort] : "title"
    end

    def set_movies_array
      if params[:title]
        @movies = Movie.find_by_title(params[:title])
      elsif params[:actor_id] && @actor = Actor.find_by_id(params[:actor_id])
        @movies = @actor.movies.order(sort_column + " " + sort_direction)
      elsif params[:genre_id] && @genre = Genre.find_by_id(params[:genre_id])
        @movies = @genre.movies.order(sort_column + " " + sort_direction)
      else
        @movies = Movie.order(sort_column + " " + sort_direction)
      end
    end

end

app/helpers/movies_helper.rb
module MoviesHelper

  def movies_display_header
    if params[:actor_id]
      "#{@actor.full_name}'s Movies"
    elsif params[:genre_id]
      "#{@genre.name}"
    else
      "Movies"
    end
  end

  def edit_movie_link
    if current_user.admin
      link_to "Edit Movie", edit_movie_path(@movie), :class => "btn btn-secondary"
    end
  end

  def display_average_rating(movie)
    if movie.reviews.size >= 1
      movie.average_rating
    else
      "N/A"
    end
  end

  def display_genre(movie, genre)
    movie_genre = MovieGenre.find_movie_genre(movie, genre).last

    content_tag :li do
      if movie && current_user.admin
        (link_to genre.name, genre_movies_path(genre)) + " - " + (link_to "delete", movie_genre_path(movie_genre), :method => :delete)
      else
        link_to genre.name, genre_movies_path(genre)
      end
    end
  end

  def display_actor(movie, actor)
    movie_actor = MovieActor.find_movie_actor(movie, actor).last

    content_tag :li do
      if movie && current_user.admin
        (link_to actor.full_name, actor_movies_path(actor)) + " - " + (link_to "delete", movie_actor_path(movie_actor), :method => :delete)
      else
        link_to actor.full_name, actor_movies_path(actor)
      end
    end
  end

end

app/views/movies/_form.html.erb
<%= form_for movie, :class => "form-group" do |f| %>
  <%= f.label "Title:" %>
  <%= f.text_field :title, :class => "form-control" %>
  <br>
  <%= f.label "Synopsis:" %>
  <%= f.text_area :synopsis, :class => "form-control" %>
  <br>
  <%= f.label "Year:" %>
  <%= f.select :year, (Date.today.year-100)..(Date.today.year), :selected => movie.year, :class => "form-control" %>
  <br>

  <%= f.label "Genre(s):" %>
  <br>
  <%= f.fields_for :genres do |genre| %>
    <div class="form-row">
      <%= genre.text_field :name, :class => "form-control col-md-6" %>
    </div>
  <% end %>
  <br>

  <%= f.label "Starring:" %>

  <%= f.fields_for :actors do |actor| %>
    <div class="form-row">
      <div class="col">
        <%= actor.text_field :first_name, :class => "form-control", :placeholder => "First name" %>
      </div>
      <div class="col">
        <%= actor.text_field :last_name, :class => "form-control", :placeholder => "Last name" %>
      </div>
    </div>
    <% end %>
    <br>
  <%= f.submit movie.persisted? ? "Update Movie" : "Add Movie", :class => "btn btn-secondary" %>
<% end %>

app/views/movies/_movies.html.erb
<table class="table">
  <thead class="thead-light">
    <tr>
      <th style="width: 50%"><%= sortable("title") %><%= sort_image("title") %></th>
      <th style="width: 25%"><%= sortable("year") %><%= sort_image("year") %></th>
      <!-- I want to be able to sort by the average rating, even though this is not a column in the db table.  -->
      <th style="width: 25%">Average Rating</th>

    </tr>
  </thead>
  <tbody>
    <% movies.each do |movie| %>
    <tr>
      <td><%= link_to movie.title, movie_path(movie) %></td>
      <td><%= movie.year %></td>
      <td><%= display_average_rating(movie) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/movies/edit.html.erb
<h1>Edit <%= @movie.title %></h1>

<%= render partial: "layouts/errors", :locals => {:object => @movie} %>

<%= render partial: "form", :locals => {:movie => @movie} %>

app/views/movies/index.html.erb
<h1><%= movies_display_header %></h1>

<% if !params[:actor_id] && !params[:genre_id] %>
  <%= form_tag movies_path, :method => :get, :class => "search-form" do %>
    <%= label_tag "Search for a movie:", nil, :class => "col-form-label" %>
    <%= text_field_tag :title, params[:title] %>

    <%= submit_tag "Search", :name => nil, :class => "btn btn-outline-secondary" %>
  <% end %>
<% end %>

<br>

<%= render partial: "movies", :locals => {:movies => @movies} %>

app/views/movies/new.html.erb
<h1>Add a Movie to the Database</h1>

<%= render partial: "layouts/errors", :locals => {:object => @movie} %>

<%= render partial: "form", :locals => {:movie => @movie} %>

app/views/movies/show.html.erb
<div class="info">
  <h1><%= @movie.title %></h1>
</div>

<div class="info">
  Genre(s):
  <ul>
    <% @movie.genres.each do |genre| %>
      <%= display_genre(@movie, genre) %>
    <% end %>
  </ul>

  Starring:
  <ul>
    <% @movie.actors.each do |actor| %>
      <%= display_actor(@movie, actor) %>
    <% end %>
  </ul>

  Synopsis:
  <p><%= @movie.synopsis %></p>
  <br>
</div>

  <%= link_to "Read Reviews", movie_reviews_path(@movie), :class => "btn btn-secondary" %>
  <%= link_to "Write a Review", new_movie_review_path(@movie), :class => "btn btn-secondary" %>
  <%= edit_movie_link %>