config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  # signup
  get "/signup" => "users#new"
  # if a user signs up incorrectly the url re-renders as /signup
  post "/signup" => "users#create"

  # login
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"

  # logout
  delete "/logout" => "sessions#destroy"

  # omniauth callback routes
  get "/auth/:provider/callback" => "sessions#omnilogin"

  resources :reviews, :movies
  resources :movie_actors, :movie_genres, only: [:destroy]
  resources :actors, :genres, only: [:index]
  resources :users, only: [:show]
  resources :movies, :users, only: [:show] do
    resources :reviews, shallow: true
  end
  resources :actors, :genres, only: [:show] do
    resources :movies, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(object.errors.count, "error") %> prohibited this <%= "#{object.class}" %> from being saved:</h3>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li class="error-list"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMovieReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <% if logged_in? && current_user.admin %>
          <div class="navbar-brand">ADMIN</div>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to "Home", user_path(current_user), :class => "nav-link" %>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Reviews
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "Write a Review", new_review_path, :class => "dropdown-item" %>
                  <%= link_to "All Reviews", reviews_path, :class => "dropdown-item" %>
                </div>
              </li>

              <% if current_user.admin %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Movies
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "Add a Movie", new_movie_path, :class => "dropdown-item" %>
                    <%= link_to "All Movies", movies_path, :class => "dropdown-item" %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Movies", movies_path, :class => "nav-link" %>
                </li>
              <% end %>

              <li class="nav-item">
                <%= link_to "Actors", actors_path, :class => "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Genres", genres_path, :class => "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", logout_path, :method => "delete", :class => "nav-link" %>
              </li>

            <% else %>
              <li class="nav-item">
                <%= link_to "Home", root_path, :class => "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign Up", signup_path, :class => "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Log In", login_path, :class => "nav-link" %>
              </li>

            <% end %>
          </ul>
        </div>
      </nav>
    </div>

    <div class="container-fluid">
      <% if flash[:message] %>
        <div class="message"><%= flash[:message] %></div>
      <% end %>

      <div class="message"><%= @error %></div>

      <%= yield %>
    </div>
  </body>
</html>